// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const PRISMA_DATABASE_URL =
  process.env.DATABASE_URL ?? "postgresql://postgres:123@localhost:5432/logrequest";
const PRISMA_SHADOW_DATABASE_URL = process.env.SHADOW_DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.mjs",
  },
  datasource: {
    url: PRISMA_DATABASE_URL,
    shadowDatabaseUrl: PRISMA_SHADOW_DATABASE_URL,
  },
});
