export const GALGOTIA_TEMPLATE_CATEGORY = "GALGOTIA_RD";

export const GALGOTIA_TEMPLATE_CODES = [
  "GU_SCOPUS_JOURNAL_PUBLICATION",
  "GU_SCOPUS_TEXTBOOK_AUTHORED",
  "GU_SCOPUS_EDITED_BOOK",
  "GU_SCOPUS_BOOK_CHAPTER",
  "GU_PHD_AWARDED",
  "GU_RESEARCH_GRANT",
  "GU_CONSULTANCY_PROJECT",
  "GU_PATENT_FILING",
  "GU_INTL_CONFERENCE_CONVENOR",
  "GU_FDP_STC_VAC_TRAINING_CONVENOR",
  "GU_CONFERENCE_PAPER",
  "GU_EDP_MDP_CONVENOR",
] as const;

export const GALGOTIA_JOURNAL_TEMPLATE_KEY = "GU_JOURNAL_PUB";
export const GALGOTIA_EDP_MDP_TEMPLATE_KEY = "GU_EDP_MDP";
export const GALGOTIA_PHD_TEMPLATE_KEY = "GU_PHD_AWARDED";
export const GALGOTIA_RESEARCH_GRANT_TEMPLATE_KEY = "GU_RESEARCH_GRANT";

export const GALGOTIA_EQUAL_SPLIT_TEMPLATE_KEYS = new Set([
  "GU_TEXTBOOK",
  "GU_EDITED_BOOK",
  "GU_BOOK_CHAPTER",
  "GU_CONSULTANCY",
  "GU_PATENT_FILING",
  "GU_CONFERENCE_PAPER",
  GALGOTIA_EDP_MDP_TEMPLATE_KEY,
]);

export const GALGOTIA_AUTO_DERIVED_SHARE_TEMPLATE_KEYS = new Set([
  GALGOTIA_JOURNAL_TEMPLATE_KEY,
  GALGOTIA_PHD_TEMPLATE_KEY,
  GALGOTIA_RESEARCH_GRANT_TEMPLATE_KEY,
  ...GALGOTIA_EQUAL_SPLIT_TEMPLATE_KEYS,
]);

export const GALGOTIA_MANUAL_CREDIT_TEMPLATE_KEYS = new Set<string>();

export const GALGOTIA_AUTO_EXCLUDE_EXTERNAL_TEMPLATE_KEYS = new Set([
  GALGOTIA_JOURNAL_TEMPLATE_KEY,
  "GU_TEXTBOOK",
  "GU_EDITED_BOOK",
  "GU_BOOK_CHAPTER",
  "GU_CONFERENCE_PAPER",
]);

export const GALGOTIA_EDITED_BOOK_TEMPLATE_KEY = "GU_EDITED_BOOK";
export const GALGOTIA_BOOK_CHAPTER_TEMPLATE_KEY = "GU_BOOK_CHAPTER";
