export const NAAC_TEMPLATE_CATEGORY = "NAAC_STARTER";
export const NAAC_UNIVERSITY_STARTER_PACK_KEY = "NAAC_UNIVERSITY_2019_FACULTY_STARTER";
export const NAAC_BODY_CODE = "NAAC";
export const NAAC_UNIVERSITY_VERSION_CODE = "UNIVERSITY_MANUAL_DEC_2019";

export const NAAC_AWARD_TEMPLATE_KEY = "NAAC_AWARD_RECOGNITION";
export const NAAC_FELLOWSHIP_TEMPLATE_KEY = "NAAC_FELLOWSHIP_SUPPORT";
export const NAAC_ECONTENT_TEMPLATE_KEY = "NAAC_ECONTENT";
export const NAAC_EXTENSION_ACTIVITY_TEMPLATE_KEY = "NAAC_EXTENSION_ACTIVITY";
export const NAAC_EXTENSION_AWARD_TEMPLATE_KEY = "NAAC_EXTENSION_AWARD";
export const NAAC_COLLAB_ACTIVITY_TEMPLATE_KEY = "NAAC_COLLAB_ACTIVITY";
export const NAAC_RESEARCH_EVENT_TEMPLATE_KEY = "NAAC_RESEARCH_EVENT";
